name: social_sim
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - matplotlib
    - numpy
    - wordcloud
    - flask
    - openai
    - anthropic
    - python-dotenv
    # - -e "git+ssh://git@github.com/schenkmanjack/NeuroEvo.git@mongodb#egg=genetic-algorithm&subdirectory=genetic_algorithm"
   
